name       : spdlog
version    : 1.11.0
release    : 5
source     :
    - https://github.com/gabime/spdlog/archive/refs/tags/v1.11.0.tar.gz : ca5cae8d6cac15dae0ec63b21d6ad3530070650f68076f3a4a862ca293a858bb
license    : MIT
homepage   : https://github.com/gabime/spdlog
component  : programming.library
summary    : Fast C++ logging library
description: |
    Fast C++ logging library
setup      : |
    %cmake_ninja \
        -DSPDLOG_BUILD_BENCH=OFF \
        -DSPDLOG_BUILD_EXAMPLES=OFF \
        -DSPDLOG_BUILD_SHARED=ON \
        -DSPDLOG_BUILD_STATIC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
