name       : spdlog
version    : 1.5.0
release    : 1
source     :
    - https://github.com/gabime/spdlog/archive/v1.5.0.tar.gz : b38e0bbef7faac2b82fed550a0c19b0d4e7f6737d5321d4fd8f216b80f8aee8a
license    : MIT
homepage   : https://github.com/gabime/spdlog
component  : programming.library
summary    : Fast C++ logging library
description: |
    Fast C++ logging library
setup      : |
    %cmake_ninja \
        -DSPDLOG_BUILD_BENCH=OFF \
        -DSPDLOG_BUILD_EXAMPLES=OFF \
        -DSPDLOG_BUILD_SHARED=ON \
        -DSPDLOG_BUILD_STATIC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
